AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
