default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todolist_api_development

test:
  <<: *default
  database: todolist_api_test

production:
  <<: *default
  database: todolist_api_production
  username: todolist_api
  password: <%= ENV['TODOLIST_API_DATABASE_PASSWORD'] %>
